# Generated by Django 2.1.4 on 2019-02-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anomologita', '0002_auto_20190222_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
