# Generated by Django 2.1.4 on 2019-02-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anomologita', '0003_remove_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='postid',
            field=models.IntegerField(default=0),
        ),
    ]
