# Generated by Django 2.1.4 on 2019-02-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anomologita', '0004_comment_postid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='postid',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Anomologita.Post'),
            preserve_default=False,
        ),
    ]
